-- Schema for Hire_Tools project

CREATE DATABASE IF NOT EXISTS finalproject;
USE finalproject;

-- Users table
CREATE TABLE IF NOT EXISTS try2 (
  id INT AUTO_INCREMENT PRIMARY KEY,
  Username VARCHAR(100) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL,
  mob VARCHAR(20) NOT NULL,
  Pass VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Rent items
CREATE TABLE IF NOT EXISTS rent (
  toolId INT AUTO_INCREMENT PRIMARY KEY,
  toolName VARCHAR(255) NOT NULL,
  Description TEXT,
  toolPrice DECIMAL(10,2) NOT NULL,
  MobileNo VARCHAR(20) NOT NULL,
  quantity INT NOT NULL,
  Image VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Sell items
CREATE TABLE IF NOT EXISTS sell (
  id INT AUTO_INCREMENT PRIMARY KEY,
  toolName VARCHAR(255) NOT NULL,
  mobile VARCHAR(20) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  email VARCHAR(255) NOT NULL,
  image VARCHAR(255),
  location VARCHAR(255) NOT NULL,
  ownerName VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
